Debug:  Modifiying workspace_utils to run directly on collab
Receiving Error below after 7 training  Epoch  on "2. Define the Network Architecture-checkpoint.ipynb" 
ConnectionError: HTTPSConnectionPool(host='nebula.udacity.com', port=443): Max retries exceeded with url: /api/v1/remote/keep-alive (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7a659e54d630>: Failed to resolve 'nebula.udacity.com' ([Errno -2] Name or service not known)"))